// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wss-design-system/Current.tsx": () => import("../components/mockups/wss-design-system/Current.tsx"),
  "./components/mockups/wss-design-system/WorldBank.tsx": () => import("../components/mockups/wss-design-system/WorldBank.tsx")
};
